name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t umer2001/synchly:latest -t umer2001/synchly:$(git rev-parse --short=7 HEAD) .
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u umer2001 --password-stdin
          docker push umer2001/synchly:latest
          docker push umer2001/synchly:$(git rev-parse --short=7 HEAD)
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
